### ISSUE TITLE
Constructor call to prepare() prevents injection in concrete macroes.

### ISSUE THREAD

**Issue by D4rkL1ch** [RobotlegsJS/RobotlegsJS-Macrobot#49]
## Expected Behavior

When extending SequenceMacro to create own initialization behaviour, I want to use injection mechanism to create payloads and guards for the commands inside macro.

## Current Behavior

prepare() method is called from the AbstractMacro constructor, which prevents injection to the super class.

## Possible Solution

prepare() method should be called after all constructors have been called.

## Steps to Reproduce (for bugs)

`@inject(AppEvent)
	private _appEvent: AppEvent;`

	public prepare(): void {
		this.atomic = false;
		const payload = new SubCommandPayload(this._appEvent.payload, GameConfig);
		this.add(InitializeSpineSymbolCacheCommand)
			.withPayloads(payload)
			.withGuards(this._appEvent.payload.slotSymbolConfig !== undefined);
		this.registerCompleteCallback(() => this._eventDispatcher.dispatchEvent(new AppEvent(AppEvent.GAME_CONNECTED, this._appEvent.payload)));
	}

## Context

Not being able to inject event that has started the macro through mapping, creates the need for additional code, which would allow me to access data from the said event.

**Comment by tiagoschenkel** [comment]
Hi @D4rkL1ch, sorry but I'm trying to understand what should be different to avoid this issue, but I was unable to find yet a solution.

Can you provide some additional solution, or how you think that your code should be when this issue is solved?

Feel free to call us directly in our [*Gitter*](https://gitter.im/RobotlegsJS/RobotlegsJS?source=orgpage) channel or send me a [*PM*]*(https://gitter.im/tiagoschenkel).

**Comment by tiagoschenkel** [comment]
@D4rkL1ch, the fix for this issue is released on version [0.2.1](https://github.com/RobotlegsJS/RobotlegsJS-Macrobot/releases/tag/0.2.1).
